version: "3.9"

services:

  app:
    build: .
    container_name: enterprise-rag-api

    ports:
      - "8000:8000"

    volumes:
      - .:/app

    depends_on:
      - postgres
      - ollama

    environment:
      DATABASE_URL: postgresql://siddharth:password@postgres:5432/enterprise_rag_db
      OLLAMA_BASE_URL: http://ollama:11434

    networks:
      - rag-network


  postgres:
    image: postgres:17

    container_name: enterprise-rag-db

    environment:
      POSTGRES_USER: siddharth
      POSTGRES_PASSWORD: password
      POSTGRES_DB: enterprise_rag_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - rag-network


  ollama:
    image: ollama/ollama

    container_name: enterprise-rag-ollama

    ports:
      - "11434:11434"

    volumes:
      - ollama_data:/root/.ollama

    networks:
      - rag-network


volumes:
  postgres_data:
  ollama_data:


networks:
  rag-network:
    driver: bridge